github: [metadata]
custom:
  zip_url: https://github.com/vsdp/vsdp-2018/archive/master.zip
  tar_url: https://github.com/vsdp/vsdp-2018/archive/master.tar.gz
  repository_url: https://github.com/vsdp/vsdp-2018/
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: false
jailed: false
incremental: true
theme: jekyll-theme-minimal
title: "VSDP"
description: "Verified SemiDefinite-quadratic-linear Programming"
logo: /res/sdp_cone.png
show_downloads: true
exclude: [benchmarks/, solver/, vsdp/]
